import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "IRSK",
  description: "Generated by create next app",
  icons: {
    icon: "/logos/irsk.jpg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased font-sans min-h-screen flex flex-col">
        <Providers>
          {/* Main content that grows to push footer down */}
          <main className="flex-grow">{children}</main>

          {/* Footer stays at the bottom */}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
