import type { Metadata } from "next";
import "./globals.css";

// ✅ Add icons field to metadata
export const metadata: Metadata = {
  title: "IRSK",
  description: "Generated by create next app",
  icons: {
    icon: "/logos/irsk.jpg", 
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased font-sans">
        {children}
      </body>
    </html>
  );
}

